name: Cadl PR Validation
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: node common/scripts/install-run-rush.js install
        name: Install JavaScript Dependencies

      - run: node packages/cadl-vs/scripts/build.js --restore
        name: Restore .NET Dependencies

      - run: node common/scripts/install-run-rush.js check
        name: Check For Dependency Version Mismatches

      - run: node common/scripts/install-run-rush.js rebuild --verbose
        name: Build

      - run: node common/scripts/install-run-rush.js test-official
        name: Test

      - run: node common/scripts/install-run-rush.js check-format
        name: Check Formatting

      - run: node eng/scripts/check-for-changed-files.js
        name: Check Git Status For Changed Files
